version: 0.0
 
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        #TaskDefinition: "arn:aws:ecs:ap-south-1:143787628822:task-definition/ecs-node-docker-td:4"
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "ecs-node-docker"
          ContainerPort: 3000
        PlatformVersion: "LATEST"