version: 0.2
### Defines the steps used by AWS CodeBuild
 
phases:
  pre_build:
    commands:
      - echo Pre-Build started on `date`
      - echo Logging in to Amazon ECR...
      - aws --version
      - docker --version
      - echo $AWS_DEFAULT_REGION
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - REPOSITORY_URI=143787628822.dkr.ecr.ap-south-1.amazonaws.com/ecs-node-docker
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo $COMMIT_HASH
      - echo $IMAGE_TAG
      - echo $REPOSITORY_URI
  build:
    commands:
      - echo Build started on `date`
      - echo $COMMIT_HASH
      - echo $IMAGE_TAG
      - echo $REPOSITORY_URI
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest -t $REPOSITORY_URI:$IMAGE_TAG -f Dockerfile .
  post_build:
    commands:
      - echo Pushing the Docker images to container registry...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG
      - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
      #- printf '[{"name":"ecs-node-docker","imageUri":"143787628822.dkr.ecr.ap-south-1.amazonaws.com/ecs-node-docker:latest"}]' > imagedefinitions.json
      #- printf '[{"name":"ecs-node-docker","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
      - echo Build completed on `date`
      - cat imageDetail.json
      - echo $REPOSITORY_URI:$IMAGE_TAG
artifacts:
  files:
    - imageDetail.json